name: Deploy to WP Engine Development Environment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3
      with:
      # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
        WPE_ENV: landinst
        # Deploy Options
        PHP_LINT: TRUE
        CACHE_CLEAR: TRUE
        SRC_PATH: "wp-content/themes/landinstitute/"
        REMOTE_PATH: "wp-content/themes/landinstitute/"